guest = ["Timmy", "Tommy", "Jimmy"]
backup_list = ["Doofy", "Goofy", "Rob"]
backup_list.insert(0, "Domonic")
backup_list.insert(3, "Rob")
backup_list.append("Milly")
print(f"{guest[0]}, You're invited")
print(f"{guest[2]}, You're invited")
print(f"{guest[1]} couldnt make it so {backup_list[0]} is welcome to come instead")
print(f"{guest[0]}, You're invited")
print(f"{guest[2]}, You're invited")
print(f"{backup_list[0]}, We found a bigger table, Everyone!")
print(f"{backup_list[3]}, We found a bigger table, Everyone!")
print(f"{backup_list[5]}, We found a bigger table, Everyone!")
print("Sadly we only have space for two since the table wont arrive on time")
backup_list.pop(0)
print(f"Sorry, {backup_list[0]}, We can't fit you in") 
backup_list.pop(1)
print(f"Sorry, {backup_list[2]}, We can't fit you in")
backup_list.pop(2)
print(f"Sorry, {backup_list[1]}, We can't fit you in")
backup_list.pop(0)
print(f"Sorry, {backup_list[0]}, We can't fit you in")
guest.pop(1)
print(f"Sorry, {guest[1]}, We can't fit you in")
print(guest)
print(backup_list)